"""Add ai_fallback to AppSettings

Revision ID: 2cbd51daf9be
Revises: abdc007904f2
Create Date: 2026-02-28 20:51:18.106421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbd51daf9be'
down_revision: Union[str, Sequence[str], None] = 'abdc007904f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('ai_fallback')

    # ### end Alembic commands ###
