"""Initial schema

Revision ID: abdc007904f2
Revises: 
Create Date: 2026-02-28 20:35:53.455816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdc007904f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Float(), server_default=sa.text('100000.0'), nullable=True),
    sa.Column('max_loss_per_trade', sa.Float(), server_default=sa.text('1000.0'), nullable=True),
    sa.Column('max_daily_loss', sa.Float(), server_default=sa.text('5000.0'), nullable=True),
    sa.Column('search_engine', sa.String(), server_default=sa.text("'ddgs'"), nullable=True),
    sa.Column('data_provider', sa.String(), server_default=sa.text("'yfinance'"), nullable=True),
    sa.Column('search_fallback', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('auto_refresh', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.Column('ai_provider', sa.String(), server_default=sa.text("'google'"), nullable=True),
    sa.Column('ai_model', sa.String(), server_default=sa.text("'gemini-3.1-pro'"), nullable=True),
    sa.Column('ai_fallback', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_usage',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('minute_requests', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('minute_tokens', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('day_requests', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('limit_rpm', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('limit_tpm', sa.Integer(), server_default=sa.text('250000'), nullable=True),
    sa.Column('limit_rpd', sa.Integer(), server_default=sa.text('20'), nullable=True),
    sa.PrimaryKeyConstraint('model_name')
    )
    op.create_index(op.f('ix_api_usage_model_name'), 'api_usage', ['model_name'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('total_trades', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('wins', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('losses', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_pnl', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('max_drawdown', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=True)
    op.create_table('dashboard_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_stocks_ticker'), 'dashboard_stocks', ['ticker'], unique=True)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('market_phase', sa.String(), nullable=True),
    sa.Column('nifty_price', sa.Float(), nullable=True),
    sa.Column('nifty_change_pct', sa.Float(), nullable=True),
    sa.Column('banknifty_price', sa.Float(), nullable=True),
    sa.Column('banknifty_change_pct', sa.Float(), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('advances', sa.Integer(), nullable=True),
    sa.Column('declines', sa.Integer(), nullable=True),
    sa.Column('sector_data_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_timestamp'), 'market_snapshots', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_1', sa.Float(), nullable=True),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'OPEN'"), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('phase_entered', sa.String(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('trailing_sl', sa.Float(), nullable=True),
    sa.Column('atr_at_entry', sa.Float(), nullable=True),
    sa.Column('risk_per_share', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('partial_exits_json', sa.Text(), nullable=True),
    sa.Column('ai_updates_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_name'), 'watchlists', ['name'], unique=True)
    op.create_table('ai_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('prompt_type', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('was_acted_upon', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('trade_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interactions_trade_date'), 'ai_interactions', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ai_interactions_timestamp'), 'ai_interactions', ['timestamp'], unique=False)
    op.create_table('watchlist_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_stocks_ticker'), 'watchlist_stocks', ['ticker'], unique=False)
    op.create_index(op.f('ix_watchlist_stocks_watchlist_id'), 'watchlist_stocks', ['watchlist_id'], unique=False)
    
    # Existing batch_alter_table calls


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('max_loss',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('risk_per_share',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('atr_at_entry',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('trailing_sl',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valid_until',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phase_entered',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_standard_signals', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('last_magic_signals', sa.TEXT(), nullable=True))
        batch_op.alter_column('max_daily_loss',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(5000.0)'))

    # ### end Alembic commands ###
    op.drop_index(op.f('ix_watchlist_stocks_watchlist_id'), table_name='watchlist_stocks')
    op.drop_index(op.f('ix_watchlist_stocks_ticker'), table_name='watchlist_stocks')
    op.drop_table('watchlist_stocks')
    op.drop_index(op.f('ix_ai_interactions_timestamp'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_trade_date'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    op.drop_index(op.f('ix_watchlists_name'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_market_snapshots_timestamp'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_dashboard_stocks_ticker'), table_name='dashboard_stocks')
    op.drop_table('dashboard_stocks')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_api_usage_model_name'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_table('app_settings')