"""add_v3_fallback_fields

Revision ID: f217dfc09ffe
Revises: 2cbd51daf9be
Create Date: 2026-03-13 15:38:51.368334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f217dfc09ffe'
down_revision: Union[str, Sequence[str], None] = '2cbd51daf9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_interactions_id'), ['id'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fallback_data', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fallback_search', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fallback_ai', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_app_settings_id'), ['id'], unique=False)
        batch_op.drop_column('search_fallback')
        batch_op.drop_column('auto_refresh')
        batch_op.drop_column('ai_fallback')

    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_summaries_id'), ['id'], unique=False)

    with op.batch_alter_table('dashboard_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_stocks_id'), ['id'], unique=False)

    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_id'), ['id'], unique=False)

    with op.batch_alter_table('watchlist_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_stocks_id'), ['id'], unique=False)

    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_id'))

    with op.batch_alter_table('watchlist_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_stocks_id'))

    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_id'))

    with op.batch_alter_table('dashboard_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_stocks_id'))

    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_summaries_id'))

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_fallback', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('auto_refresh', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('search_fallback', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_index(batch_op.f('ix_app_settings_id'))
        batch_op.drop_column('fallback_ai')
        batch_op.drop_column('fallback_search')
        batch_op.drop_column('fallback_data')

    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_interactions_id'))

    # ### end Alembic commands ###
